version: '3.8'

services:
  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
    driver: local